App\Infrastructure\Category\Query\Projections\CategoryView:
    type: entity
    table: category
    id:
        id:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        deleted:
            type: boolean
            nullable: false
            length: 1
            options:
                fixed: false
                default: 0
    lifecycleCallbacks: {  }
