App\Infrastructure\User\Query\Projections\UserView:
    type: entity
    table: fos_user
    id:
        id:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true

    fields:

        avatar:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        steemit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        banned:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
