parameters:
    env(DATABASE_HOST): 'db'
    env(DATABASE_PORT): '3306'
    env(DATABASE_NAME): 'tutorials_tank'
    env(DATABASE_USER): 'root'
    env(DATABASE_PASS): 'admin'

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   "%env(DATABASE_NAME)%"
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASS)%"
        charset:  UTF8
        server_version: '5.7'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Projections:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/orm/projections'
                prefix: 'App\Infrastructure'
                alias: Projections
