sudo: required

services:
  - docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.21.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v
  - docker -v
  - cp .env.dist .env
  - cat .env
before_script:
  - composer self-update --rollback
  - composer install

script:
  - make

