# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:1.11-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - db
      - php
    networks:
      - code-network

  php:
    build: ./docker/php
    container_name: tutorials_tank_php
    working_dir: /var/www/project
    volumes:
      - ./:/var/www/project
    links:
      - db
    networks:
      - code-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - code-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
    restart: always
    ports:
     - 8000:80
    volumes:
     - /sessions
    networks:
      - code-network

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - 5601:5601
    volumes:
      - ./docker/kibana/config:/usr/share/kibana/config/kibana.yml
    networks:
      - code-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports:
      - "9200:9200"
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
    
volumes:
  db_data:
