# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - db
      - php

  php:
    build: ./docker/php
    working_dir: /var/www/project
    volumes:
      - ./:/var/www/project
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
    restart: always
    ports:
     - 8000:80
    volumes:
     - /sessions
